name: test
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
      - dev
      - fix-4
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Semver #your environment name
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      